@startuml
class Transfer {
- Integer id
- Integer accountId
- TransferType type
- Date time
- Double amount
}
class FundTrade {
- Integer id
- Integer accountId
- String code
- FundTradeType type
- Date time
- Double price
- Integer amount
}
class Assets {
- Integer id
- Double totalAssets
- Double stockAssets
- Double balance
- Double fundAssets
}
class Account {
- Integer id
- String name
- String password
+ boolean equals(Object)
+ int hashCode()
}
class StockHis {
- Integer id
- String ticker
- String name
- Date time
- Double currentPrice
- Double openPrice
- Double highPrice
- Double lowPrice
- Double closePrice
- Double vol
}
class FundHis {
- Integer id
- String code
- Date time
- Double unitNet
- Double accNet
- Double rate
- String subscription
- String redemption
}
class FundHold {
- Integer id
- Integer accountId
- String code
- Double subscriptionPrice
- Integer amount
}
class StockHold {
- Integer id
- int accountId
- String ticker
- Double callPrice
- Integer amount
}
class Stock {
- String ticker
- String name
- Date time
- Double currentPrice
- Double openPrice
- Double highPrice
- Double lowPrice
- Double closePrice
- Double vol
}
class Fund {
- String code
- Date time
- Double unitNet
- Double accNet
- Double rate
- String subscription
- String redemption
}
class Trade {
- Integer id
- Integer accountId
- String ticker
- TradeType type
- Date time
- Double price
- Integer amount
}
@enduml