@startuml
interface com.portfolio.mgmtsys.repository.TransferRepo {
}
interface com.portfolio.mgmtsys.service.StockService {
}
class com.portfolio.mgmtsys.model.Request {
}
interface com.portfolio.mgmtsys.service.FundHoldService {
}
class com.portfolio.mgmtsys.controller.StockHoldController {
+ ResponseEntity<Object> getAllStockHold(Integer)
+ ResponseEntity<Object> buyStock(BuyAndSellStockRequest)
+ ResponseEntity<Object> sellStock(BuyAndSellStockRequest)
+ ResponseEntity<Object> getTrades(Integer,String,String)
+ ResponseEntity<Object> getAllStockHoldTrend(Integer,String,String)
}
class com.portfolio.mgmtsys.domain.StockHis {
+ <<Create>> StockHis(String)
+ <<Create>> StockHis()
}
enum com.portfolio.mgmtsys.enumeration.FundTradeType {
+  SUBSCRIBE
+  REDEEM
}
interface com.portfolio.mgmtsys.service.StockHoldService {
}
class com.portfolio.mgmtsys.domain.FundHold {
+ <<Create>> FundHold(Integer,String)
+ <<Create>> FundHold(Integer)
+ <<Create>> FundHold()
+ String toString()
}
interface com.portfolio.mgmtsys.repository.StockHisRepo {
}
class com.portfolio.mgmtsys.model.MyStockResponse {
+ <<Create>> MyStockResponse(String,String,Integer,Double)
+ String getStockName()
+ void setStockName(String)
+ String getTicker()
+ void setTicker(String)
+ Integer getAmount()
+ void setAmount(Integer)
+ Double getCurrentPrice()
+ void setCurrentPrice(Double)
+ String toString()
}
interface com.portfolio.mgmtsys.service.FundService {
}
interface com.portfolio.mgmtsys.repository.AssetsRepo {
}
interface com.portfolio.mgmtsys.repository.FundTradeRepo {
}
class com.portfolio.mgmtsys.domain.FundHis {
}
interface com.portfolio.mgmtsys.repository.FundRepo {
}
interface com.portfolio.mgmtsys.service.AssetsService {
}
class com.portfolio.mgmtsys.model.GetTrendRequest {
+ <<Create>> GetTrendRequest(Integer,Date,Date)
+ <<Create>> GetTrendRequest()
+ <<Create>> GetTrendRequest(Integer,String,String)
+ Integer getAccountId()
+ void setAccountId(Integer)
}
class com.portfolio.mgmtsys.task.ScheduledTask {
+ void scheduleUpdateAsserts()
}
enum com.portfolio.mgmtsys.enumeration.TransferType {
+  OUT
+  IN
}
class com.portfolio.mgmtsys.model.BuyAndSellStockRequest {
+ Integer getAccountId()
+ void setAccountId(Integer)
+ String getTicker()
+ void setTicker(String)
+ Integer getAmount()
+ void setAmount(Integer)
}
class com.portfolio.mgmtsys.domain.Assets {
}
interface com.portfolio.mgmtsys.repository.AccountRepo {
}
class com.portfolio.mgmtsys.service.impl.FundHoldServiceImpl {
+ List<FundHold> getAllFundHold(Integer)
+ boolean buyFund(BuyAndSellFundRequest)
+ boolean sellFund(BuyAndSellFundRequest)
+ LinkedList<FundTrade> getTrades(GetTradesRequest)
+ LinkedList<GetFundTrendResponse> getAllFundHoldTrend(GetTrendRequest)
}
class com.portfolio.mgmtsys.model.GetFundHisRequest {
+ <<Create>> GetFundHisRequest(String,Date,Date)
+ <<Create>> GetFundHisRequest()
+ <<Create>> GetFundHisRequest(String,String,String)
+ String getCode()
+ void setCode(String)
}
interface com.portfolio.mgmtsys.repository.StockRepo {
}
class com.portfolio.mgmtsys.service.impl.StockHoldServiceImpl {
+ Stock findStockByTicker(String)
+ StockHold findStockHoldByTickerAndAccount(String,Integer)
+ LinkedList<MyStockResponse> getAllStockHold(Integer)
+ boolean buyStock(BuyAndSellStockRequest)
+ boolean sellStock(BuyAndSellStockRequest)
+ LinkedList<Trade> getTrades(GetTradesRequest)
+ LinkedList<GetStockTrendResponse> getAllStockHoldTrend(GetTrendRequest)
+ List<StockHis> findStockHis(String,Date,Date)
}
class com.portfolio.mgmtsys.domain.Stock {
}
class com.portfolio.mgmtsys.utils.TimeUtil {
+ {static} Date getNowTime()
+ {static} Date[] extractedTime(TimeRequest)
+ {static} Specification<T> timeLimit(Date,Date,Example<T>)
}
class com.portfolio.mgmtsys.domain.Transfer {
}
class com.portfolio.mgmtsys.domain.FundTrade {
+ <<Create>> FundTrade(Integer,String,FundTradeType,Date,Double,Integer)
+ <<Create>> FundTrade()
}
class com.portfolio.mgmtsys.aspect.CheckBalanceAspect {
+ void checkBalance(JoinPoint)
}
class com.portfolio.mgmtsys.domain.Account {
+ boolean equals(Object)
+ int hashCode()
}
class com.portfolio.mgmtsys.service.impl.AssetsServiceImpl {
+ Assets getAssetsById(Integer)
+ Assets transferIn(Map<String,Object>)
+ Assets transferOut(Map<String,Object>)
}
class com.portfolio.mgmtsys.model.BuyAndSellFundRequest {
+ Integer getAccountId()
+ void setAccountId(Integer)
+ String getCode()
+ void setCode(String)
+ Integer getAmount()
+ void setAmount(Integer)
+ String toString()
}
class com.portfolio.mgmtsys.model.GetTradesRequest {
+ <<Create>> GetTradesRequest(Integer,Date,Date)
+ <<Create>> GetTradesRequest()
+ <<Create>> GetTradesRequest(Integer,String,String)
+ Integer getAccountId()
+ void setAccountId(Integer)
+ String toString()
}
class com.portfolio.mgmtsys.controller.FundHoldController {
+ ResponseEntity<Object> getAllStockHold(Integer)
+ ResponseEntity<Object> buyFund(BuyAndSellFundRequest)
+ ResponseEntity<Object> sellFund(BuyAndSellFundRequest)
+ ResponseEntity<Object> sellFund(Integer,String,String)
+ ResponseEntity<Object> getAllStockHoldTrend(Integer,String,String)
}
class com.portfolio.mgmtsys.domain.StockHold {
+ <<Create>> StockHold(int)
+ <<Create>> StockHold()
}
class com.portfolio.mgmtsys.controller.AssetsController {
+ ResponseEntity<Object> getAssetsById(Integer)
+ ResponseEntity<Object> transferIn(Map<String,Object>)
+ ResponseEntity<Object> transferOut(Map<String,Object>)
}
interface com.portfolio.mgmtsys.repository.TradeRepo {
}
class com.portfolio.mgmtsys.model.GetStockHisRequest {
+ <<Create>> GetStockHisRequest(String,Date,Date)
+ <<Create>> GetStockHisRequest()
+ <<Create>> GetStockHisRequest(String,String,String)
+ String getTicker()
+ void setTicker(String)
}
enum com.portfolio.mgmtsys.enumeration.TradeType {
+  SELL
+  BUY
}
class com.portfolio.mgmtsys.model.GetFundTrendResponse {
+ String getCode()
+ void setCode(String)
+ List<Double> getPrices()
+ void setPrices(List<Double>)
+ List<Date> getDates()
+ void setDates(List<Date>)
+ String toString()
+ void addDates(Date[])
}
class com.portfolio.mgmtsys.service.impl.AccountServiceImpl {
+ Integer login(Account)
+ Account register(Account)
}
class com.portfolio.mgmtsys.domain.Trade {
+ <<Create>> Trade()
+ <<Create>> Trade(Integer,String,TradeType,Date,Double,Integer)
}
class com.portfolio.mgmtsys.controller.StockController {
+ ResponseEntity<Object> getAllStocks(Integer,Integer)
+ ResponseEntity<Object> searchStock(Map<String,Object>)
+ ResponseEntity<Object> getStockByTicker(String)
+ ResponseEntity<Object> getStockHis(String,String,String)
}
class com.portfolio.mgmtsys.model.Response {
}
class com.portfolio.mgmtsys.controller.AccountController {
+ ResponseEntity<Object> login(Account)
+ ResponseEntity<Object> register(Account)
}
class com.portfolio.mgmtsys.Application {
+ {static} void main(String[])
}
class com.portfolio.mgmtsys.service.impl.FundServiceImpl {
+ List<Fund> getAllFunds(Integer,Integer)
+ List<Fund> searchFund(Map<String,Object>)
+ Fund getFundByCode(String)
+ List<FundHis> getFundHis(GetFundHisRequest)
}
class com.portfolio.mgmtsys.domain.Fund {
+ <<Create>> Fund()
+ <<Create>> Fund(String)
}
class com.portfolio.mgmtsys.model.TimeRequest {
+ <<Create>> TimeRequest(Date,Date)
+ <<Create>> TimeRequest(String,String)
+ <<Create>> TimeRequest()
+ Date getStartTime()
+ void setStartTime(Date)
+ Date getEndTime()
+ void setEndTime(Date)
}
class com.portfolio.mgmtsys.controller.FundController {
+ ResponseEntity<Object> getAllFunds(Integer,Integer)
+ ResponseEntity<Object> searchFund(Map<String,Object>)
+ ResponseEntity<Object> getFundByCode(String)
+ ResponseEntity<Object> getFundHis(String,String,String)
}
interface com.portfolio.mgmtsys.repository.FundHisRepo {
}
interface com.portfolio.mgmtsys.repository.FundHoldRepo {
}
interface com.portfolio.mgmtsys.repository.StockHoldRepo {
}
class com.portfolio.mgmtsys.service.impl.StockServiceImpl {
+ List<Stock> getAllStocks(Integer,Integer)
+ List<Stock> searchStock(Map<String,Object>)
+ Stock getStockByTicker(String)
+ List<StockHis> getStockHis(GetStockHisRequest)
}
interface com.portfolio.mgmtsys.service.AccountService {
}
class com.portfolio.mgmtsys.model.GetStockTrendResponse {
+ String getName()
+ void setName(String)
+ String getTicker()
+ void setTicker(String)
+ List<Double> getPrices()
+ void setPrices(List<Double>)
+ List<Date> getDates()
+ void setDates(List<Date>)
+ String toString()
+ void addDates(Date[])
}


org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.TransferRepo
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.StockHisRepo
org.springframework.data.jpa.repository.JpaSpecificationExecutor <|-- com.portfolio.mgmtsys.repository.StockHisRepo
com.portfolio.mgmtsys.model.Response <|-- com.portfolio.mgmtsys.model.MyStockResponse
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.AssetsRepo
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.FundTradeRepo
org.springframework.data.jpa.repository.JpaSpecificationExecutor <|-- com.portfolio.mgmtsys.repository.FundTradeRepo
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.FundRepo
com.portfolio.mgmtsys.model.TimeRequest <|-- com.portfolio.mgmtsys.model.GetTrendRequest
com.portfolio.mgmtsys.model.Request <|-- com.portfolio.mgmtsys.model.BuyAndSellStockRequest
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.AccountRepo
com.portfolio.mgmtsys.service.FundHoldService <|.. com.portfolio.mgmtsys.service.impl.FundHoldServiceImpl
com.portfolio.mgmtsys.model.TimeRequest <|-- com.portfolio.mgmtsys.model.GetFundHisRequest
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.StockRepo
com.portfolio.mgmtsys.service.StockHoldService <|.. com.portfolio.mgmtsys.service.impl.StockHoldServiceImpl
com.portfolio.mgmtsys.service.AssetsService <|.. com.portfolio.mgmtsys.service.impl.AssetsServiceImpl
com.portfolio.mgmtsys.model.Request <|-- com.portfolio.mgmtsys.model.BuyAndSellFundRequest
com.portfolio.mgmtsys.model.TimeRequest <|-- com.portfolio.mgmtsys.model.GetTradesRequest
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.TradeRepo
org.springframework.data.jpa.repository.JpaSpecificationExecutor <|-- com.portfolio.mgmtsys.repository.TradeRepo
com.portfolio.mgmtsys.model.TimeRequest <|-- com.portfolio.mgmtsys.model.GetStockHisRequest
com.portfolio.mgmtsys.model.Response <|-- com.portfolio.mgmtsys.model.GetFundTrendResponse
com.portfolio.mgmtsys.service.AccountService <|.. com.portfolio.mgmtsys.service.impl.AccountServiceImpl
com.portfolio.mgmtsys.service.FundService <|.. com.portfolio.mgmtsys.service.impl.FundServiceImpl
com.portfolio.mgmtsys.model.Request <|-- com.portfolio.mgmtsys.model.TimeRequest
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.FundHisRepo
org.springframework.data.jpa.repository.JpaSpecificationExecutor <|-- com.portfolio.mgmtsys.repository.FundHisRepo
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.FundHoldRepo
org.springframework.data.jpa.repository.JpaRepository <|-- com.portfolio.mgmtsys.repository.StockHoldRepo
com.portfolio.mgmtsys.service.StockService <|.. com.portfolio.mgmtsys.service.impl.StockServiceImpl
com.portfolio.mgmtsys.model.Response <|-- com.portfolio.mgmtsys.model.GetStockTrendResponse
@enduml